services:
  - type: web
    name: LocoBot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python discordbot.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
